module.exports = {
  WEBSITE_RED: '#FF5959FF',
  DESKTOP_BREAKPOINT: 1000,
  TABLET_BREAKPOINT: 576,
  VIEWS: Object.freeze({"DESKTOP": 0, "TABLET": 1, "MOBILE": 2}),
  STORAGE_LOCATION_PREFIX: 'locations',
  HOVER_COLOR: '#24202080',
  COVER_COLOR: '#FF5959FF',
  TRANSITION_TYPE: Object.freeze({"COVER": 0, "HOVER": 1, "NONE": 2}),
  FADE_IN_TIMEOUT: 1250,
  IMG_COUNTS: Object.freeze({"MOBILE": 12, "TABLET": 6, "DESKTOP": 4}),
}
